# Generated by Django 2.0.6 on 2018-06-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Social_Groups',
        ),
    ]
