# Generated by Django 2.0.6 on 2018-06-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnet', '0002_auto_20180610_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_Groups',
            new_name='Group',
        ),
    ]
